M48
; DRILL file {KiCad 9.0.2} date 2025-06-23T20:15:22+0200
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-06-23T20:15:22+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.2
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C1.270
%
G90
G05
T1
X118.72Y-64.61
X118.72Y-70.39
T2
X101.13Y-45.42
M30
